src/FamilyLaw.Hub.Web/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyLaw.Hub.Web.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

src/FamilyLaw.Hub.Web/Pages/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyLaw.Hub.Web.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/FamilyLaw.Hub.Web/Pages/ConfirmEmail.cshtml.cs
using System;
using System.Threading.Tasks;
using FamilyLaw.Hub.Web.Infrastructure.Persistence.Model;
using FamilyLaw.Hub.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyLaw.Hub.Web.Pages
{
    [AllowAnonymous]
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<User> _userManager;

        public ConfirmEmailModel(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            var result = await _userManager.ConfirmEmailAsync(user, code);
            if (!result.Succeeded)
            {
                throw new InvalidOperationException($"Error confirming email for user with ID '{userId}':");
            }

            return Page();
        }
    }
}

src/FamilyLaw.Hub.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyLaw.Hub.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/FamilyLaw.Hub.Web/Pages/ExternalLogin.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Threading.Tasks;
using FamilyLaw.Hub.Web.Infrastructure.Persistence.Model;
using FamilyLaw.Hub.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FamilyLaw.Hub.Web.Pages
{
    [AllowAnonymous]
    public class ExternalLoginModel : PageModel
    {
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;
        private readonly ILogger<ExternalLoginModel> _logger;

        public ExternalLoginModel(
            SignInManager<User> signInManager,
            UserManager<User> userManager,
            ILogger<ExternalLoginModel> logger)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string LoginProvider { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public IActionResult OnGetAsync()
        {
            return RedirectToPage("./Login");
        }

        public IActionResult OnPost(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Page("./ExternalLogin", pageHandler: "Callback", values: new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetCallbackAsync(string returnUrl = null, string remoteError = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (remoteError != null)
            {
                ErrorMessage = $"Error from external provider: {remoteError}";
                return RedirectToPage("./Login", new {ReturnUrl = returnUrl });
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                ErrorMessage = "Error loading external login information.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }

            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor : true);
            if (result.Succeeded)
            {
                _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", info.Principal.Identity.Name, info.LoginProvider);
                return LocalRedirect(returnUrl);
            }
            if (result.IsLockedOut)
            {
                return RedirectToPage("./Lockout");
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
                ReturnUrl = returnUrl;
                LoginProvider = info.LoginProvider;
                if (info.Principal.HasClaim(c => c.Type == ClaimTypes.Email))
                {
                    Input = new InputModel
                    {
                        Email = info.Principal.FindFirstValue(ClaimTypes.Email)
                    };
                }
                return Page();
            }
        }

        public async Task<IActionResult> OnPostConfirmationAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            // Get the information about the user from the external login provider
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                ErrorMessage = "Error loading external login information during confirmation.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }

            if (ModelState.IsValid)
            {
                var user = new User { UserName = Input.Email, Email = Input.Email };
                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await _userManager.AddLoginAsync(user, info);
                    if (result.Succeeded)
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        _logger.LogInformation("User created an account using {Name} provider.", info.LoginProvider);
                        return LocalRedirect(returnUrl);
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            LoginProvider = info.LoginProvider;
            ReturnUrl = returnUrl;
            return Page();
        }
    }
}

src/FamilyLaw.Hub.Web/Pages/ForgotPassword.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using FamilyLaw.Hub.Web.Infrastructure.Persistence.Model;
using FamilyLaw.Hub.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyLaw.Hub.Web.Pages
{
    [AllowAnonymous]
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly IEmailSender _emailSender;

        public ForgotPasswordModel(UserManager<User> userManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please 
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                var callbackUrl = Url.Page(
                    "ResetPassword",
                    pageHandler: null,
                    values: new { code },
                    protocol: Request.Scheme);

                await _emailSender.SendEmailAsync(
                    Input.Email,
                    "Reset Password",
                    $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

src/FamilyLaw.Hub.Web/Pages/ForgotPasswordConfirmation.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyLaw.Hub.Web.Pages
{
    [AllowAnonymous]
    public class ForgotPasswordConfirmation : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/FamilyLaw.Hub.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using FamilyLaw.Hub.Web.Infrastructure;
using FamilyLaw.Hub.Web.Infrastructure.Persistence.Context;
using FamilyLaw.Hub.Web.Infrastructure.Persistence.Model;
using FamilyLaw.Hub.Web.Infrastructure.Persistence.Model.Enquiry;
using FamilyLaw.Hub.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FamilyLaw.Hub.Web.Pages
{
    [BindProperties]
    public class IndexModel : PageModel
    {
        private readonly FamilyLawDbContext _dbContext;
        private readonly IEmailSender _emailSender;
        private readonly UserManager<User> _userManager;

        [Required(ErrorMessage = "Please enter your First Name", AllowEmptyStrings = false)]
        [StringLength(25)]
        public string FirstName { get; set; }


        [Required(ErrorMessage = "Please enter your Last Name", AllowEmptyStrings = false)]
        [StringLength(25)]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter your email address")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]
        public string EmailAddress { get; set; }


        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{4})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Please enter a valid phone number")]
        public string PhoneNumber { get; set; }

        public string Gender { get; set; }

        public List<SelectListItem> Genders { get; set; }

        public int AdviceType { get; set; }

        public List<SelectListItem> HowDidYouFoundUsOptions { get; set; }

        public string HowDidYouFoundUs { get; set; }

        public List<SelectListItem> AdviceTypes { get; set; }

        [Required(ErrorMessage = "Please enter your details about your familly matter", AllowEmptyStrings = false)]
        [StringLength(500)]
        public string FamilyMatter { get; set; }

        [StringLength(500)]
        public string ArgumentsWithPartner { get; set; }

        [StringLength(500)]
        public string ArgumentsWithFamily { get; set; }

        [StringLength(500)]
        public string InjuryFromFamily { get; set; }

        [StringLength(500)]
        public string HowSafeDoYouFeel { get; set; }

        [StringLength(500)]
        public string SpecialNeeds { get; set; }

        [StringLength(500)]
        public string SpecialNeedsChildren { get; set; }

        [StringLength(500)]
        public string RiskToChildren { get; set; }


        public IndexModel(FamilyLawDbContext dbContext, IEmailSender emailSender, UserManager<User> userManager)
        {
            _dbContext = dbContext;
            _emailSender = emailSender;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGet()
        {
            Genders = DropdownViewModel.GetGenders();
            HowDidYouFoundUsOptions = DropdownViewModel.GetMarketingOptions();

            AdviceTypes = await _dbContext.AdviceTypes.OrderBy(x => x.Name)
                .Select(x => new SelectListItem(x.Name,
                    x.Id.ToString()))
                .ToListAsync();

            return Page();
        }


        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var model = new CaseEnquiry
            {
                FirstName = FirstName,
                LastName = LastName,
                EmailAddress = EmailAddress,
                Phone = PhoneNumber,
                Gender = Gender,
                AdviceTypeId = AdviceType,
                FamilyMatter = FamilyMatter,
                ArgumentsWithPartner = ArgumentsWithPartner,
                ArgumentsWithFamily = ArgumentsWithFamily,
                HowSafeDoYouFeel = HowSafeDoYouFeel,
                SpecialNeeds = SpecialNeeds,
                SpecialNeedsChildren = SpecialNeedsChildren,
                RiskToChildren = RiskToChildren,
                HowDidYouFoundUs = HowDidYouFoundUs,
                Created = DateTime.UtcNow,
                Status = Status.AwaitingResponse
            };

            _dbContext.Enquiries.Add(model);

            await _dbContext.SaveChangesAsync();
            TempData["SubmitSuccess"] = true;

            await NotifyAdministrators(model.Id);

            return RedirectToPage("Success");
        }

        /// <summary>
        /// Notify Administrators
        /// </summary>
        /// <returns></returns>
        public async Task NotifyAdministrators(int enquiryId)
        {
            var adminUsers = await _userManager.GetUsersInRoleAsync(Roles.Administrator);

            var callbackUrl = Url.Page(
                "Admin/Enquiries/View",
                pageHandler: null,
                values: new { id = enquiryId },
                protocol: Request.Scheme);


            foreach (var user in adminUsers)
            {
                await _emailSender.SendEmailAsync(user.Email, "A new enquiry has been submitted!", 
                    $@"You have a new enquiry, please check <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>family law hub case management system</a>.");
            }
        }
    }
}

src/FamilyLaw.Hub.Web/Pages/Lockout.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyLaw.Hub.Web.Pages
{
    [AllowAnonymous]
    public class LockoutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/FamilyLaw.Hub.Web/Pages/Logout.cshtml.cs
using System.Threading.Tasks;
using FamilyLaw.Hub.Web.Infrastructure.Persistence.Model;
using FamilyLaw.Hub.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FamilyLaw.Hub.Web.Pages
{
    [AllowAnonymous]
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<User> _signInManager;
        private readonly ILogger<LogoutModel> _logger;

        public LogoutModel(SignInManager<User> signInManager, ILogger<LogoutModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return LocalRedirect("/Logout");
        }
    }
}

src/FamilyLaw.Hub.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyLaw.Hub.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/FamilyLaw.Hub.Web/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

src/FamilyLaw.Hub.Web/Pages/AccessDenied.cshtml
@page
@model AccessDeniedModel
@{
    ViewData["Title"] = "Access denied";
}

<header>
    <h1 class="text-danger">@ViewData["Title"]</h1>
    <p class="text-danger">You do not have access to this resource.</p>
</header>

src/FamilyLaw.Hub.Web/Pages/ConfirmEmail.cshtml
@page
@model ConfirmEmailModel
@{
    ViewData["Title"] = "Confirm email";
}

<h2>@ViewData["Title"]</h2>
<div>
    <p>
        Thank you for confirming your email.
    </p>
</div>

src/FamilyLaw.Hub.Web/Pages/ExternalLogin.cshtml
@page
@model ExternalLoginModel
@{
    ViewData["Title"] = "Register";
}

<h2>@ViewData["Title"]</h2>
<h4>Associate your @Model.LoginProvider account.</h4>
<hr />

<p class="text-info">
    You've successfully authenticated with <strong>@Model.LoginProvider</strong>.
    Please enter an email address for this site below and click the Register button to finish
    logging in.
</p>

<div class="row">
    <div class="col-md-4">
        <form asp-page-handler="Confirmation" asp-route-returnUrl="@Model.ReturnUrl" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.Email"></label>
                <input asp-for="Input.Email" class="form-control" />
                <span asp-validation-for="Input.Email" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-outline-primary">Register</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/FamilyLaw.Hub.Web/Pages/ForgotPassword.cshtml
@page
@model ForgotPasswordModel
@{
    ViewData["Title"] = "Forgot your password?";
}

<h2>@ViewData["Title"]</h2>
<h4>Enter your email.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.Email"></label>
                <input asp-for="Input.Email" class="form-control" />
                <span asp-validation-for="Input.Email" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-outline-primary">Submit</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/FamilyLaw.Hub.Web/Pages/ForgotPasswordConfirmation.cshtml
@page
@model ForgotPasswordConfirmation
@{
    ViewData["Title"] = "Forgot password confirmation";
}

<h2>@ViewData["Title"]</h2>
<p>
    Please check your email to reset your password.
</p>

src/FamilyLaw.Hub.Web/Pages/Index.cshtml
@page
@model IndexModel
@{ ViewData["Title"] = "We are here to help"; }
<div class="col-12">
    <div class="row">
        <div class="col-md-7">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title display-4 border-bottom pb-4 ml-3 " style="font-size: 27px;">Family Law Hub @("@") LSBU</h5>
                    <p class="m-3">
                        The family law hub @("@") LSBU offers to help people who do not have a lawyer with family law problems.  The service is provided by volunteer students.  We offer information and support with legal problems. We are not qualified to give legal advice, but our input might provide you with the information and support that you need to make important decisions for you and your family.
                    </p>
                    
                    <p class="m-3">
                        Please fill out the following sections if you need help with a family law problem.
                    </p>
                    <div class="col-md-12">
                        <form method="post">
                            <div class="form-group">
                                <label asp-for="FirstName">First Name<span class="text-danger">*</span></label>
                                <input asp-for="FirstName" class="form-control" placeholder="Please enter your first name" />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="LastName">Last Name<span class="text-danger">*</span></label>
                                <input asp-for="LastName" class="form-control" placeholder="Please enter your last name" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EmailAddress">Email Address<span class="text-danger">*</span></label>
                                <input asp-for="EmailAddress" class="form-control" placeholder="Please enter your email address" />
                                <span asp-validation-for="EmailAddress" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="PhoneNumber">Phone Number</label>
                                <input asp-for="PhoneNumber" class="form-control" placeholder="Please enter your phone number" />
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Gender">Gender</label>
                                <select asp-for="Gender" asp-items="Model.Genders" class="form-control"></select>
                            </div>
                            
                            <div class="form-group">
                                <label asp-for="HowDidYouFoundUs">How did you find out about the service?</label>
                                <select asp-for="HowDidYouFoundUs" asp-items="Model.HowDidYouFoundUsOptions" class="form-control"></select>
                            </div>

                            <div class="form-group">
                                <label asp-for="AdviceType">Which areas do you need advice?</label>
                                <select asp-for="AdviceType" asp-items="Model.AdviceTypes" class="form-control"></select>
                            </div>

                            <div class="form-group">
                                <label asp-for="FamilyMatter">Family matter<span class="text-danger">*</span></label>
                                <textarea asp-for="FamilyMatter" class="form-control" placeholder="Please give a brief detail around the matter to which you wish to receive legal advice" rows="3"></textarea>
                                <span asp-validation-for="FamilyMatter" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ArgumentsWithPartner">If there are any arguments with your former partner, what usually happens?</label>
                                <textarea asp-for="ArgumentsWithPartner" class="form-control" placeholder="Please provide brief details if this is applicable" rows="3"></textarea>
                            </div>

                            <div class="form-group">
                                <label asp-for="ArgumentsWithFamily">Do you generally have a lot of arguments within your family/home environment?</label>
                                <textarea asp-for="ArgumentsWithFamily" class="form-control" placeholder="Please provide brief details if this is applicable" rows="3"></textarea>
                            </div>

                            <div class="form-group">
                                <label asp-for="InjuryFromFamily">Have you ever sustained an injury or caused an injury in a home environment?</label>
                                <textarea asp-for="InjuryFromFamily" class="form-control" placeholder="Please provide brief details if this is applicable" rows="3"></textarea>
                            </div>

                            <div class="form-group">
                                <label asp-for="HowSafeDoYouFeel">How safe do you and/or your family feel currently?</label>
                                <textarea asp-for="HowSafeDoYouFeel" class="form-control" placeholder="Please provide brief details if this is applicable" rows="3"></textarea>
                            </div>

                            <div class="form-group">
                                <label asp-for="SpecialNeeds">Do you have any special requirements that we may need to be aware of?</label>
                                <textarea asp-for="SpecialNeeds" class="form-control" placeholder="Please provide brief details if this is applicable" rows="3"></textarea>
                            </div>

                            <div class="form-group">
                                <label asp-for="SpecialNeedsChildren">Do any of your children have any special needs?</label>
                                <textarea asp-for="SpecialNeedsChildren" class="form-control" placeholder="Please provide brief details if this is applicable" rows="3"></textarea>
                            </div>


                            <div class="form-group">
                                <label asp-for="RiskToChildren">Are you or your children at any risk of harm?</label>
                                <textarea asp-for="RiskToChildren" class="form-control" placeholder="Please provide brief details if this is applicable" rows="3"></textarea>
                            </div>

                            <button type="submit" class="btn btn-outline-primary">Save</button>
                        </form>
                    </div>


                </div>
            </div>

        </div>
        @*<div class="col-md-5">

            <img class="col-lg-12" src="https://www.lsbu.ac.uk/__data/assets/image/0019/263413/Student-prizes.jpg" class="mg-responsive"  alt="..."/>
        </div>*@

    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


}

src/FamilyLaw.Hub.Web/Pages/Login.cshtml
@page
@model LoginModel

@{
    ViewData["Title"] = "Login";
}

<div class="col-12">
  
    <div class="col-md-4">
        <div>
            <h2 class="display-4" style="font-size: 27px;">@ViewData["Title"]</h2>
        </div>
        <section>
            <form method="post">
                <hr/>
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Input.Email"></label>
                    <input asp-for="Input.Email" class="form-control"/>
                    <span asp-validation-for="Input.Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.Password"></label>
                    <input asp-for="Input.Password" class="form-control"/>
                    <span asp-validation-for="Input.Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label asp-for="Input.RememberMe">
                            <input asp-for="Input.RememberMe"/>
                            @Html.DisplayNameFor(m => m.Input.RememberMe)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-primary">Login</button>
                </div>
                <div class="form-group">
                    <p>
                        <a asp-page="./ForgotPassword">Forgot your password?</a>
                    </p>
                </div>
            </form>
        </section>
    </div>
    <div class="col-md-6 col-md-offset-2">

    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/FamilyLaw.Hub.Web/Pages/LoginWith2fa.cshtml
@page
@model LoginWith2faModel
@{
    ViewData["Title"] = "Two-factor authentication";
}

<h2>@ViewData["Title"]</h2>
<hr />
<p>Your login is protected with an authenticator app. Enter your authenticator code below.</p>
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-route-returnUrl="@Model.ReturnUrl">
            <input asp-for="RememberMe" type="hidden" />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.TwoFactorCode"></label>
                <input asp-for="Input.TwoFactorCode" class="form-control" autocomplete="off" />
                <span asp-validation-for="Input.TwoFactorCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label asp-for="Input.RememberMachine">
                        <input asp-for="Input.RememberMachine" />
                        @Html.DisplayNameFor(m => m.Input.RememberMachine)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary">Log in</button>
            </div>
        </form>
    </div>
</div>
<p>
    Don't have access to your authenticator device? You can 
    <a asp-page="./LoginWithRecoveryCode" asp-route-returnUrl="@Model.ReturnUrl">log in with a recovery code</a>.
</p>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}